package com.infinitehits.bubbleblast.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.media.SoundPool
import android.util.Log
import com.infinitehits.bubbleblast.R
import com.infinitehits.bubbleblast.data.SettingsManager

/**
 * Every sound the game makes.
 *
 * Sound effects go through a single [SoundPool] (nine tiny samples, loaded once,
 * played many times, lower latency than MediaPlayer) while the two music beds
 * use looping [MediaPlayer] instances.
 *
 * The manager is owned by [com.infinitehits.bubbleblast.AppServices] and lives as
 * long as the process, so nothing here is tied to an Activity lifecycle and there
 * is nothing to leak.
 */
class AudioManager(
    private val context: Context,
    private val settings: SettingsManager
) {

    /** Which music bed should be playing. */
    enum class Scene { NONE, HOME, GAME }

    /** All sound effects. Files live in `res/raw` and are generated by `tools/generate_audio.py`. */
    enum class Sfx(val resId: Int, val volume: Float) {
        SHOOT(R.raw.sfx_shoot, 0.55f),
        POP(R.raw.sfx_pop, 0.85f),
        DROP(R.raw.sfx_drop, 0.7f),
        COMBO(R.raw.sfx_combo, 0.8f),
        POWER_UP(R.raw.sfx_powerup, 0.8f),
        STAR(R.raw.sfx_star, 0.75f),
        LEVEL_COMPLETE(R.raw.sfx_level_complete, 0.9f),
        GAME_OVER(R.raw.sfx_game_over, 0.9f),
        CLICK(R.raw.sfx_click, 0.6f)
    }

    private var soundPool: SoundPool? = null
    private val soundIds = HashMap<Sfx, Int>()
    private val loadedIds = HashSet<Int>()

    private var musicPlayer: MediaPlayer? = null
    private var currentScene: Scene = Scene.NONE
    private var applicationInForeground: Boolean = true
    private var released: Boolean = false

    val isMusicPlaying: Boolean
        get() = musicPlayer?.isPlaying == true

    // ------------------------------------------------------------------
    // Setup
    // ------------------------------------------------------------------

    /** Loads the effects. Safe to call more than once. */
    fun initialize() {
        if (soundPool != null || released) return
        val attributes = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_GAME)
            .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
            .build()

        val pool = SoundPool.Builder()
            .setMaxStreams(MAX_STREAMS)
            .setAudioAttributes(attributes)
            .build()
        pool.setOnLoadCompleteListener { _, sampleId, status ->
            if (status == 0) loadedIds.add(sampleId)
        }
        soundPool = pool

        for (sfx in Sfx.entries) {
            try {
                soundIds[sfx] = pool.load(context, sfx.resId, 1)
            } catch (error: Exception) {
                Log.w(TAG, "Could not load sound ${sfx.name}", error)
            }
        }
    }

    // ------------------------------------------------------------------
    // Effects
    // ------------------------------------------------------------------

    /**
     * Plays a sound effect.
     * @param rate playback speed, 0.5 = one octave down; used to pitch pops with the combo
     */
    fun play(sfx: Sfx, rate: Float = 1f, volumeScale: Float = 1f) {
        if (!settings.soundEnabled) return
        val pool = soundPool ?: return
        val id = soundIds[sfx] ?: return
        if (!loadedIds.contains(id)) return
        val volume = (sfx.volume * volumeScale).coerceIn(0f, 1f)
        val playbackRate = rate.coerceIn(0.5f, 2f)
        pool.play(id, volume, volume, 1, 0, playbackRate)
    }

    /** Convenience: the pop sound rises in pitch with the combo counter. */
    fun playPop(combo: Int) {
        val rate = (1f + (combo - 1) * 0.09f).coerceIn(0.85f, 1.9f)
        play(Sfx.POP, rate)
    }

    // ------------------------------------------------------------------
    // Music
    // ------------------------------------------------------------------

    /** Switches the music bed. Ignored when music is disabled in the settings. */
    fun setScene(scene: Scene) {
        currentScene = scene
        applyMusic()
    }

    /** Called from the lifecycle observer when the app leaves the foreground. */
    fun setForeground(foreground: Boolean) {
        applicationInForeground = foreground
        if (foreground) {
            applyMusic()
        } else {
            musicPlayer?.let { if (it.isPlaying) it.pause() }
        }
    }

    /** Re-applies the settings after the player toggles sound or music. */
    fun onSettingsChanged() {
        if (!settings.soundEnabled) {
            soundPool?.autoPause()
        } else {
            soundPool?.autoResume()
        }
        applyMusic()
    }

    private fun applyMusic() {
        if (released) return
        val shouldPlay = settings.musicEnabled &&
            applicationInForeground &&
            (currentScene == Scene.HOME || currentScene == Scene.GAME)

        if (!shouldPlay) {
            musicPlayer?.let { if (it.isPlaying) it.pause() }
            return
        }

        val resId = when (currentScene) {
            Scene.HOME -> R.raw.music_home
            Scene.GAME -> R.raw.music_game
            Scene.NONE -> return
        }

        val player = musicPlayer
        if (player != null && player.isPlaying) return

        if (player == null) {
            createMusicPlayer(resId)
        } else {
            // Same instance, different bed: swap the data source.
            try {
                player.reset()
                player.setDataSource(context.resources.openRawResourceFd(resId))
                player.prepare()
                player.start()
            } catch (error: Exception) {
                Log.w(TAG, "Could not switch music track", error)
                releaseMusic()
            }
        }
    }

    private fun createMusicPlayer(resId: Int) {
        try {
            val descriptor = context.resources.openRawResourceFd(resId) ?: return
            val player = MediaPlayer()
            player.setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_GAME)
                    .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                    .build()
            )
            player.setDataSource(descriptor.fileDescriptor, descriptor.startOffset, descriptor.length)
            descriptor.close()
            player.isLooping = true
            player.setVolume(MUSIC_VOLUME, MUSIC_VOLUME)
            player.prepare()
            player.start()
            musicPlayer = player
        } catch (error: Exception) {
            Log.w(TAG, "Could not start music", error)
            releaseMusic()
        }
    }

    private fun releaseMusic() {
        musicPlayer?.let {
            try {
                it.stop()
            } catch (ignored: IllegalStateException) {
                // Already stopped - nothing to do.
            }
            it.release()
        }
        musicPlayer = null
    }

    // ------------------------------------------------------------------
    // Teardown
    // ------------------------------------------------------------------

    /** Releases every native resource. The process owning this manager is shutting down. */
    fun release() {
        released = true
        releaseMusic()
        soundPool?.release()
        soundPool = null
        soundIds.clear()
        loadedIds.clear()
    }

    companion object {
        private const val TAG = "AudioManager"
        private const val MAX_STREAMS = 8
        private const val MUSIC_VOLUME = 0.45f
    }
}
